export const ITEMS = [
	{
		id: 1,
		name: "Earthy Brown",
		desc: "Stylish brown sneakers with a rustic feel, for a sophisticated look.",
		price: 40,
		image: "/pic1.png",
	},
	{
		id: 2,
		name: "White & beige",
		desc: "Stylish blue head warmer to keep you warm in the cold",
		price: 20,
		image: "/pic2.png",
	},
	{
		id: 3,
		name: "Classic Runners",
		desc: "Timeless sneakers comfortable fit, ideal for everyday wear.",
		price: 30,
		image: "/pic3.png",
	},
	{
		id: 4,
		name: "White sneakers",
		desc: "Elegant white sneakers with minimalist aesthetic.",
		price: 50,
		image: "/pic4.png",
	},
	{
		id: 5,
		name: "Black & Beige",
		desc: "Trendy black sneakers with beige accents, ideal for street fashion.",
		price: 25,
		image: "/pic5.png",
	},
	{
		id: 6,
		name: "Urban Kicks",
		desc: "Urban sneakers, a bold urban look, ideal for streetwear enthusiasts",
		price: 100,
		image: "/pic6.png",
	},
	{
		id: 7,
		name: "Bold Red",
		desc: "Vibrant red lines perfect for adding a pop of color to your outfit",
		price: 60,
		image: "/pic7.png",
	},
	{
		id: 8,
		name: "Classic Retro",
		desc: "Retro sneakers, a mix of white, black, and red, with a vintage vibe",
		price: 40,
		image: "/pic8.png",
	},
	{
		id: 9,
		name: "Bold Urban",
		desc: "Chunky, Stylish sneakers with a distinct urban look.",
		price: 35,
		image: "/pic9.png",
	},
	{
		id: 10,
		name: "Olive Green",
		desc: "Casual sneakers ideal for a laid-back yet stylish look",
		price: 55,
		image: "/pic10.png",
	},
	{
		id: 11,
		name: "Multi-Color",
		desc: "Eye-catching bold multi-color sneakers, ideal to standout",
		price: 80,
		image: "/pic11.png",
	},
	{
		id: 12,
		name: "Sage Green",
		desc: "Sleek green sneakers with brown soles, perfect for casual wear.",
		price: 45,
		image: "/pic12.png",
	},
	{
		id: 13,
		name: "Vintage Red...",
		desc: "Red lined sneakers with a vintage feel, perfect for everyday style.",
		price: 30,
		image: "/pic13.png",
	},
	{
		id: 14,
		name: "Khaki Green",
		desc: "khaki green sneakers with a relaxed design, perfect for everyday wear.",
		price: 45,
		image: "/pic14.png",
	},
	{
		id: 15,
		name: "Sleek green",
		desc: "Elegant suede sneakers, perfect for polished casual outfit",
		price: 60,
		image: "/pic15.png",
	},
	{
		id: 16,
		name: "Retro kicks",
		desc: "Sporty sneakers with a retro vibe and eye catching red detailing",
		price: 75,
		image: "/pic16.png",
	},
];
